### ISSUE TITLE
Adding points

### ISSUE THREAD

**Issue by rghertner** [arilamstein/choroplethr#11]
I've made some beautiful maps showing county-level data, and now I want to be able to add points for major cities. Is there a way to add ggplot geom_points to a choroplethr object? 

For example, I'd like to do the following:
```
county_choropleth(dt,state_zoom = c("mississippi"))+
scale_fill_manual(guide=FALSE,name="Relationship",values = cols9,na.value="white")+
geom_point(data=cities, aes(x=lon, y=lat), color="red")
```
but I get the following error:

> Error in eval(expr, envir, enclos) : object 'group' not found

My one guess is this may have to do in part to projection issues, but I don't really know how to get the projection from the choroplethr object.

**Comment by arilamstein** [comment]
Yes, this is indeed possible, but looking at the code and error it's not exactly clear to me what the error is. Normally when people need help using choroplethr on their project I provide it through my membership site:

arilamstein.com/membership
