### ISSUE TITLE
Names on regions?

### ISSUE THREAD

**Issue by Deleetdk** [arilamstein/choroplethr#12]
Very nice package!

For my map, I want to add the names of the regions to the plot. This is apparently automatically done when mapping US states, at least [it looks like that in the examples](https://cran.r-project.org/web/packages/choroplethr/vignettes/b-state-choropleth.html). However, it is not done when mapping e.g. Argentinian provinces ([or Japanese, in the example](https://cran.r-project.org/web/packages/choroplethr/vignettes/i-creating-admin1-maps.html)), which I am.

How do I put names on the regions?

**Comment by arilamstein** [comment]
I believe that for the US I simply place the text as the (x,y) coordinates
that are the average of each point in the state.

If you want help doing this for another state, I recommend joining my
membership site:

arilamstein.com/membership

I help people with problems there like that every day there.

**Comment by Deleetdk** [comment]
It's better to have things in the open. [Here's a reproducible example](http://rpubs.com/EmilOWK/209498) for other people wondering how to get names on.
